### ISSUE TITLE
Installing on remote server 

### ISSUE THREAD

**Issue by andrewbanchich** [nasa/isle#2]
I'm a novice to a lot of the stuff mentioned in Isle's Read Me installation instructions. I would ideally like to install this on my website so I can access it at http://mydomain.com from anywhere. I purchase hosting from Namecheap.

How would I go about installing it like that? Is it possible?

Any help would be greatly appreciated. This system looks absolutely perfect for what I need.

**Comment by bruffridge** [comment]
It might be possible if NameCheap allows you to customize the apache conf file or create your own. There will probably be some bugs you have to work out. I use some ini_set commands for example that may be disabled by NameCheap. See if you can get it to work, and then post about the process. I'm sure there are others that would benefit from a tutorial.

**Comment by andrewbanchich** [comment]
How about using DigitalOcean? Since my last comment I've switched to them and gotten some comman line experience. I set up an Ubuntu droplet and installed PHP and MySQL, installed Vagrant, ran `vagrant init`, installed VirtualBox, cloned ISLE, and ran `vagrant up`, but I get the following error message:

> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> vm:
> - The box 'base' could not be found.

What am I doing wrong? Again, totally new to this. If I do it this way through DigitalOcean, does that mean I'll be able to use ISLE remotely by visiting that droplet's IP address?

Thanks

**Comment by bruffridge** [comment]
Make sure you are running `vagrant up` from the directory the Vagrantfile is located in. Honestly though  I wouldn't use Vagrant at all on the production server. Make sure your server has apache. Copy the files over and manually run the commands in isle-init.sh. I would read about what each command does to make sure you understand before you run it, you might have to change some of the paths to match your environment. You can learn about configuring apache here: https://httpd.apache.org/docs/current/configuring.html
