### ISSUE TITLE
Error with php version 7

### ISSUE THREAD

**Issue by c1sc0** [nasa/isle#3]
I installed without virtualbox on my server, but i get the following error: `Uncaught PHP exception (Code 0): Function name must be a string in /var/www/webroot/isle/remoteInterface.php on line 346` the problem was solved by changing the line to: `$rows = $svc->{$_REQUEST['method']}(...);`

**Comment by bruffridge** [comment]
Thanks for sharing your problem and also the solution!

**Comment by PeteDiMarco** [comment]
I ran a fresh copy of ISLE using Vagrant and VirtualBox on top of Windows 7.  ISLE did not work out of the box.  There were several errors like the one c1sc0 found.  My changes are attached:
[isle-git.txt](https://github.com/nasa/isle/files/1195454/isle-git.txt)
I'm not a PHP programmer so I can't guarantee my changes are correct.
