### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by Plinzen** [nasa/isle#6]
Hi,
thanks for this great community contribution. 
Do have you plan to support LDAP for user management?

Thanks and best regards
Christopher

**Comment by bruffridge** [comment]
There are no plans to add LDAP support at this time. LDAP support can be added by using the [PHP LDAP functions](http://php.net/manual/en/book.ldap.php) by following [this basic format](http://php.net/manual/en/ldap.using.php).

One use might be to create a function that queries your LDAP server for employees to add to the "Add User" dropdown by editing [this line](https://github.com/nasa/isle/blob/master/webroot/isle/users.php#L23).
