### ISSUE TITLE
Running without Vagrant or VirtualBox.

### ISSUE THREAD

**Issue by chanakaDe** [nasa/isle#7]
Hi guys,
This is great. I really love this work and also this is superb again.
I have a question. I am running LAMP stack. My OS is Arch Linux and I have others to. PHP , MySQL and Apache. Can I run this like a normal application ? Copy and paste files to apache http folder. (like www folder) and configure the database. Like that ? Because I'm not a good fan of Vagrant. 

And also why we need VirtualBox ? To create a virtual Linux env ?
I am going to use this for my university lab. 
so it's nice if I can run it via localhost.. Just as another PHP application.

And also have you used any framework for this ? Like Laravel or CodeIgnitor ?

**Comment by chanakaDe** [comment]
Hey guys, we suppose to discuss issues and ideas here. No ?
Is that inactive repository ?

**Comment by chanakaDe** [comment]
@bruffridge Are you there ?

**Comment by bruffridge** [comment]
Yes, it can be run without vagrant or virtualbox. Those are just if you want an easy way to run it in a local VM, but if you already are familiar with setting up a LAMP server, you can just as easily deploy the code there as well. In fact, that's the way it was designed and run in both development and production, vagrant was just added on as an option when I put the code on github to make it easier for someone to run it without needing to know how to configure a server.

We didn't use Laravel or CodeIgnitor for this, we used a custom PHP object-oriented framework my colleague developed.

**Comment by chanakaDe** [comment]
@bruffridge  Sorry for asking a lot and disturbing you. This is me. https://github.com/chanakaDe
And I am trying to configure this to my university lab. We also need the same. First I need to run this on my local machine. I have Arch Linux. And also XAMPP installed. I cloned the project into my '/opt/lampp/htdocs/isle-master' location. It's the server location of Arch Linux. And I think your document root is 'webroot'. So I typed 'http://localhost/isle-master/webroot/' in browser and it only gives me "Enter your inventory URL.". Is there any wrong with my local setup ? I didn't still dumped the database table. 

And also please tell me where I can get database script to restore to my local mysql instance. 

And also when I go to 'http://localhost/isle-master/webroot/isle' , I get this message.
"Object not found!"...... I think there's something wrong with re-write engine. I have to use .php to get that location. I have experience in Laravel and CodeIgnitor. But this is little different.

Can you please guide me on this ? to setup this on my local machine ?
Then I can take a Digital Ocean droplet and host this to use in my university. 
And we can mention your support on our university web blog.

Please reply me when you can. Waiting for it.

**Comment by chanakaDe** [comment]
@bruffridge Hey brother, if you are busy, can you please provide me a way to configure this out ?
